[package]
name = "r1cs-crypto"
version = "0.4.0"
authors = [
    "Sean Bowe",
    "Alessandro Chiesa",
    "Matthew Green",
    "Ian Miers",
    "Pratyush Mishra",
    "Howard Wu",
    "Daniele Di Benedetto <daniele@horizenlabs.io>",
    "Marcelo Kaihara",
    "Ulrich Haboeck <ulrich@horizenlabs.io>",
    "Maksym Vereshchak <phoinic@gmail.com>",
    "Luigi Varriale <luigi@horizenlabs.io>",
    "cronicc <cronic@horizenlabs.io>",
    "Luca Giussani <lucagiussani@horizenlabs.io>",
    "Daniele Di Tullio <danieled@horizenlabs.io>",
    "Nicholas Mainardi <nicholas@horizenlabs.io>"
]
description = "A crypto library for constraint system gadgets"
include = ["Cargo.toml", "src", "README.md", "LICENSE-APACHE", "LICENSE-MIT"]
license = "MIT/Apache-2.0"
edition = "2018"

################################# Dependencies ################################

[dependencies]
algebra = { path = "../../../algebra", features = [ "parallel" ] }
primitives = {path = "../../../primitives"}
r1cs-core = { path = "../../core" }
r1cs-std = { path = "../std"}
proof-systems = { path = "../../../proof-systems", features = ["groth16", "gm17"], optional = true }
bench-utils = { path = "../../../bench-utils" }

digest = { version = "0.8.1", optional = true }
blake2 = { version = "0.8.1", optional = true }
ripemd160 = { version = "0.9.1", optional = true }
sha2 = { version = "0.9.5", optional = true }
hex = { version = "0.4.3", optional = true }

rand = { version = "0.8.4" }
derivative = "2.2.0"
rayon = "1.5.1"
rayon-core = "~1.9.1"

[features]
commitment = ["primitives/commitment", "prf"]
merkle_tree = ["primitives/merkle_tree"]
prf = ["digest", "blake2", "ripemd160", "sha2", "hex", "primitives/prf"]
signature = ["primitives/signature", "digest"]
vrf = ["primitives/vrf"]
nizk = ["proof-systems"]

# For Poseidon CRH / Merkle Tree
mnt4_753 = ["primitives/mnt4_753"]
mnt6_753 = ["primitives/mnt6_753"]
tweedle = ["primitives/tweedle"]
bn_382 = ["primitives/bn_382"]

llvm_asm = ["algebra/llvm_asm"]

[dev-dependencies]
rand_xorshift = { version = "0.3.0" }
algebra = { path = "../../../algebra", features = ["bls12_377", "bls12_381", "sw6", "bn_382"] }
r1cs-std = { path = "../std", features = ["jubjub", "edwards_sw6", "bls12_377", "mnt4_753", "mnt6_753", "bn_382", "tweedle"] }
r1cs-crypto = { path = "../crypto", features = ["mnt4_753", "mnt6_753", "bn_382", "tweedle"] }
